In [76]:
%run project1.py

In [78]:
%run test.py

PASS Import project1
PASS Get order 
FAIL Hinge loss single : not implemented
FAIL Hinge loss full : not implemented
FAIL Perceptron single update : not implemented
FAIL Perceptron : not implemented
FAIL Average perceptron : not implemented
FAIL Pegasos single update : not implemented
FAIL Pegasos : not implemented
FAIL Classify : not implemented
FAIL Classifier accuracy : not implemented
PASS Bag of words 
WARN Bag of words : does not remove stopwords: ['he', 'is', 'on', 'the', 'there', 'to']
PASS Extract bow feature vectors
WARN Extract bow feature vectors : uses binary indicators as features


In [59]:
def hinge_loss_single(feature_vector, label, theta, theta_0):
    """
    Finds the hinge loss on a single data point given specific classification
    parameters.

    Args:
        feature_vector - A numpy array describing the given data point.
        label - A real valued number, the correct classification of the data
            point.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given data point and parameters.
    """
    # Your code here
    #print("hi")
    #for i, x in enumerate(feature_vector):
    if ((np.dot(feature_vector, theta)+theta_0)*label)>=1:
        return 0
    else:
        return 1-(np.dot(feature_vector, theta)+theta_0)*label
    raise NotImplementedError
#pragma: coderesponse end

In [232]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -0.2

hinge_loss_single(feature_vector, label, theta, theta_0)

0.19999999999999996

In [70]:
def check_hinge_loss_single():
    ex_name = "Hinge loss single"

    feature_vector = np.array([1, 2])
    label, theta, theta_0 = 1, np.array([-1, 1]), -0.2
    exp_res = 1 - 0.8
    if check_real(
            ex_name, hinge_loss_single,
            exp_res, feature_vector, label, theta, theta_0):
        return
    log(green("PASS"), ex_name, "")

In [71]:
a=check_hinge_loss_single

In [73]:
a()

PASS Hinge loss single 


In [56]:
label*(np.dot(feature_vector, theta)+theta_0)

0.8

In [54]:
feature_vector

array([1, 2])

<H1> 
HINGE LOSS COMPLETE

In [191]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    
    # Your code here
    total_hinge= 0
    for i in range(len(feature_matrix)):
        total_hinge= total_hinge+ hinge_loss_single(feature_matrix[i], labels[i], theta, theta_0)
        
    return total_hinge/ len(feature_matrix)
    raise NotImplementedError


In [192]:
def check_hinge_loss_full():
    ex_name = "Hinge loss full"

    feature_vector = np.array([[1, 2], [1, 2]])
    label, theta, theta_0 = np.array([1, 1]), np.array([-1, 1]), -0.2
    exp_res = 1 - 0.8
    if check_real(
            ex_name, hinge_loss_full,
            exp_res, feature_vector, label, theta, theta_0):
        return

    log(green("PASS"), ex_name, "")

In [193]:
check_hinge_loss_full()

PASS Hinge loss full 


In [138]:
hinge_loss_full(feature_vector,label,theta,theta_0)

0.19999999999999996

In [121]:
theta

array([-1,  1])

In [166]:
feature_vector[1]

array([1, 2])

In [158]:
len(feature_vector)

2

In [181]:
loss=np.max([0.0,1-(label[1]*(np.dot(theta,feature_vector[1]) + theta_0))])

In [180]:
np.max([0,1-(label[1]*(np.dot(theta,feature_vector[1]) + theta_0))])

0.19999999999999996

In [179]:
np.max([0.0,a])


0.19999999999999996

In [211]:
 #np.array([[1, 2],[1, 2]],[[1, 2],[1, 2]])
a=np.array([[[1, 2],[1, 2]],[[5, 2],[5, 2]]])

In [202]:
list([1,2])

[1, 2]

In [212]:
a[1]

array([[5, 2],
       [5, 2]])

In [230]:
def hinge_loss_single1(feature_vector, label, theta, theta_0):
    temp=label*(feature_vector.dot(theta)+theta_0)
    return np.max([0.0,1-temp])
    


In [235]:
feature_vector = np.array([[1, 2],[2,2]])
label, theta, theta_0 = 1, np.array([-1, 1]), -0.2

hinge_loss_single1(feature_vector[0],label, theta, theta_0)

0.19999999999999996

In [241]:
#label, theta, theta_0 = 1, np.array([-1, 1]), -0.2
#[np.max([0.0,1-label*(feature_vector[i].dot(theta)+theta_0)]) for i in feature_vector-1]

In [239]:
[i for i in feature_vector]

[array([1, 2]), array([2, 2])]

<h1> Perceptron Algorithm

In [330]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
       
    # Your code here
    theta=current_theta
    theta_0=current_theta_0
    
    for i in range(len(feature_vector)):
        print(i)
        if(label[i]*(np.dot(feature_vector[i],theta)+theta_0))<=0:
            theta+=label[i]*feature_vector[i]
            theta_0+=label[i]
    
    return theta,theta_0
    raise NotImplementedError


In [334]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -1.5
feature_vector[0]

1

In [332]:
def check_perceptron_single_update():
    ex_name = "Perceptron single update"

    feature_vector = np.array([1, 2])
    label, theta, theta_0 = 1, np.array([-1, 1]), -1.5
    exp_res = (np.array([0, 3]), -0.5)
    if check_tuple(
            ex_name, perceptron_single_step_update,
            exp_res, feature_vector, label, theta, theta_0):
        return

    feature_vector = np.array([1, 2])
    label, theta, theta_0 = 1, np.array([-1, 1]), -1
    exp_res = (np.array([0, 3]), 0)
    if check_tuple(
            ex_name + " (boundary case)", perceptron_single_step_update,
            exp_res, feature_vector, label, theta, theta_0):
        return

    log(green("PASS"), ex_name, "")
check_perceptron_single_update()

0


TypeError: 'int' object is not subscriptable

In [291]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    # Your code here
    current_theta=[feature_matrix.shape[0],]
    print(current_theta)
    current_theta_0=0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            # Your code here
            theta,theta_0 = perceptron_single_step_update([i],labels[i],current_theta,current_theta_0)
            pass
    return theta,theta_0
    raise NotImplementedError


In [292]:
def check_perceptron():
    ex_name = "Perceptron"

    feature_matrix = np.array([[1, 2]])
    labels = np.array([1])
    T = 1
    exp_res = (np.array([1, 2]), 1)
    if check_tuple(
            ex_name, perceptron,
            exp_res, feature_matrix, labels, T):
        return

    feature_matrix = np.array([[1, 2], [-1, 0]])
    labels = np.array([1, 1])
    T = 1
    exp_res = (np.array([0, 2]), 2)
    if check_tuple(
            ex_name, perceptron,
            exp_res, feature_matrix, labels, T):
        return

    feature_matrix = np.array([[1, 2]])
    labels = np.array([1])
    T = 2
    exp_res = (np.array([1, 2]), 1)
    if check_tuple(
            ex_name, perceptron,
            exp_res, feature_matrix, labels, T):
        return

    feature_matrix = np.array([[1, 2], [-1, 0]])
    labels = np.array([1, 1])
    T = 2
    exp_res = (np.array([0, 2]), 2)
    if check_tuple(
            ex_name, perceptron,
            exp_res, feature_matrix, labels, T):
        return

    log(green("PASS"), ex_name, "")

check_perceptron()

[1]
FAIL Perceptron : incorrect answer. Expected (array([1, 2]), 1) , got:  ([1, 0], 1)


In [311]:
feature_matrix = np.array([[1, 2], [-1, 0]])
labels = np.array([1, 1])
current_theta=np.array([0,0])
T = 2


In [331]:
theta,theta_0 = perceptron_single_step_update(feature_matrix[0],labels,current_theta,0)
print(theta,theta_0)

0
1
[1 1] 1


In [314]:
feature_matrix[1]

array([-1,  0])

In [315]:
labels

array([1, 1])

In [324]:
labels[1]

1