In [4]:
import numpy as np

In [5]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    return np.random.random([n,1])
    raise NotImplementedError


In [6]:
randomization(2)

array([[0.57640524],
       [0.89625125]])

In [7]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A=np.random.random([h,w])
    B=np.random.random([h,w])
    s=A+B
    return A,B,s
    raise NotImplementedError


In [20]:
A,B,s=operations(1,2)

In [21]:
A

array([[0.53607036, 0.25298445]])

In [22]:
B

array([[0.93300627, 0.06294582]])

In [12]:
s

array([[0.86718403, 0.22765397],
       [0.33703469, 1.46696633]])

In [13]:
%run test.py

PASS NumPy installed
PASS SciPy installed
PASS matplotlib installed
PASS PyTorch installed
PASS tqdm installed


In [24]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s=np.linalg.norm(A+B)
    return s
    raise NotImplementedError


In [25]:
norm(A,B)

1.5026636595076048

In [26]:
A


array([[0.53607036, 0.25298445]])

In [27]:
B

array([[0.93300627, 0.06294582]])

In [28]:
np.linalg.norm(A)

0.592766868650787

In [29]:
np.linalg.norm(B)

0.9351271984985045

In [57]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    return np.tanh(np.matmul(weights.transpose(),inputs))
    raise NotImplementedError


In [64]:
inputs=np.array([[2],[3]])
weights=np.array([[0],[0]])

In [65]:
z=neural_network(inputs, weights)

In [66]:
z

array([[0.]])

In [147]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    #if x<=y:
    #    return x*y 
    #else:
    #    x/y
    return [x*y if x<=y else x/y]
    raise NotImplementedError


In [148]:
scalar_function(3,3)

[9]

In [149]:
def vector_function(x,y):
    vscalar_function=np.vectorize(scalar_function)
    return vscalar_function(x,y)

In [150]:
vscalar_function([1],[1])

array([1])

In [144]:
vector_function([1,2,3],[1,5,6])

array([ 1, 10, 18])

In [119]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    a=np.vectorize(scalar_function)
    return a(x,y)
    raise NotImplementedError


In [133]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b
    #return [a-b if a>b else a+b]

In [134]:
vfunc = np.vectorize(myfunc)

In [138]:
vfunc([1, 2, 3, 4], [2,3,2,1])

array([3, 5, 1, 3])

In [102]:
vfunc([2,3,4],[2])

array([4, 1, 2])

In [154]:
x=100
pdb.set_trace()

y=200




--Return--
> <ipython-input-154-4c71955ff361>(2)<module>()->None
-> pdb.set_trace()


(Pdb)  x


100


(Pdb)  y


200


(Pdb)  l


  1  	x=100
  2  ->	pdb.set_trace()
  3  	
  4  	y=200
  5  	
  6  	
[EOF]


(Pdb)  n


> c:\users\prasanna\appdata\local\programs\python\python37\lib\site-packages\ipython\core\interactiveshell.py(3299)run_code()
-> sys.excepthook = old_excepthook


(Pdb)  c
